adds a warning message in pre-start

diff --git a/sbin/ntlm-auth-api-docker-wrapper b/sbin/ntlm-auth-api-docker-wrapper
--- a/sbin/ntlm-auth-api-docker-wrapper
+++ b/sbin/ntlm-auth-api-docker-wrapper
@@ -5,13 +5,17 @@ source /usr/local/pf/containers/systemd-service
 name=ntlm-auth-api
 
 conf_dir="/usr/local/pf/var/conf/${name}.d/"
-cd $conf_dir || exit 1
+cd $conf_dir || {
+    echo "Can not locate config dir: /usr/local/pf/var/conf/${name}.d/. Service unable to start."
+    exit 1
+}
 env_files=$(ls *.env 2>/dev/null)
 cd - || exit 1
 
 option=$1
 
 if [ -z "$env_files" ]; then
+    echo "No .env file found in /usr/local/pf/var/conf/${name}.d/. Service unable to start. Do you have a valid domain.conf, or manually edited domain.conf without a pfcmd configreload ?"
     exit 1
 fi
 
@@ -23,7 +27,7 @@ fi
 if [ "$option" = "start" ]; then
     for env_file in $env_files; do
         iden=$(echo $env_file | awk -F '.' '{print $1}')
-        echo "starting ntlm auth api domain service for: $iden using env file: $env_file"
+        echo "Starting ntlm auth api domain service for: $iden using env file: $env_file"
         systemctl start packetfence-ntlm-auth-api-domain@"$iden" &
     done
     /usr/local/pf/sbin/ntlm-auth-api-monitor &
@@ -37,7 +41,7 @@ elif [ "$option" = "stop" ]; then
 
     for env_file in $env_files; do
         iden=$(echo $env_file | awk -F '.' '{print $1}')
-        echo "stopping ntlm auth api domain service for: $iden"
+        echo "Stopping ntlm auth api domain service for: $iden"
         systemctl stop packetfence-ntlm-auth-api-domain@"$iden" &
     done
 
@@ -45,14 +49,14 @@ elif [ "$option" = "stop" ]; then
     while true; do
         svcs=$(docker ps | grep "ntlm-auth-api-")
         if [ -n "$svcs" ]; then
-            failures=$((failures+1))
+            failures=$((failures + 1))
         else
             echo "Stopped."
             break
         fi
-        
+
         if [ $failures -gt 30 ]; then
-            echo "some of the containers failed to stop after 30s, please check for details"
+            echo "Some sub services failed to stop after 30s. Please check running containers docker ps | grep ntlm-auth-api for sub service details"
             exit 1
         fi
 
