Fix/ntlm auth api service status (#8091)
* move db config to dedicated file.

* move db config to dedicated file.

* adds a service monitor for forking

* adds monitor script file to spec.

* always generate db.ini

* kill the monitor before we handle the sub services

* fix service alive status

---------

Co-authored-by: Darren Satkunas <dsatkuna@akamai.com>

diff --git a/sbin/ntlm-auth-api-docker-wrapper b/sbin/ntlm-auth-api-docker-wrapper
--- a/sbin/ntlm-auth-api-docker-wrapper
+++ b/sbin/ntlm-auth-api-docker-wrapper
@@ -5,7 +5,10 @@ source /usr/local/pf/containers/systemd-service
 name=ntlm-auth-api
 
 conf_dir="/usr/local/pf/var/conf/${name}.d/"
-env_files=$(ls $conf_dir 2>/dev/null)
+cd $conf_dir || exit 1
+env_files=$(ls *.env 2>/dev/null)
+cd - || exit 1
+
 option=$1
 
 if [ -z "$env_files" ]; then
@@ -21,15 +24,41 @@ if [ "$option" = "start" ]; then
     for env_file in $env_files; do
         iden=$(echo $env_file | awk -F '.' '{print $1}')
         echo "starting ntlm auth api domain service for: $iden using env file: $env_file"
-        systemctl start packetfence-ntlm-auth-api-domain@"$iden"
+        systemctl start packetfence-ntlm-auth-api-domain@"$iden" &
     done
-    sleep infinity
+    /usr/local/pf/sbin/ntlm-auth-api-monitor &
 elif [ "$option" = "stop" ]; then
+    pids=$(pgrep "ntlm-auth-api-monitor")
+
+    if [ -n "$pids" ]; then
+        echo "$pids" | xargs kill
+        echo '' >/usr/local/pf/var/run/ntlm-auth-api.pid
+    fi
+
     for env_file in $env_files; do
         iden=$(echo $env_file | awk -F '.' '{print $1}')
         echo "stopping ntlm auth api domain service for: $iden"
-        systemctl stop packetfence-ntlm-auth-api-domain@"$iden"
+        systemctl stop packetfence-ntlm-auth-api-domain@"$iden" &
     done
+
+    failures=0
+    while true; do
+        svcs=$(docker ps | grep "ntlm-auth-api-")
+        if [ -n "$svcs" ]; then
+            failures=$((failures+1))
+        else
+            echo "Stopped."
+            break
+        fi
+        
+        if [ $failures -gt 30 ]; then
+            echo "some of the containers failed to stop after 30s, please check for details"
+            exit 1
+        fi
+
+        sleep 1
+    done
+
     echo "stopped"
     sleep 1
 fi
