apply part of #6875 to maintenance

diff --git a/addons/vagrant/cumulus/Vagrantfile b/addons/vagrant/cumulus/Vagrantfile
--- a/addons/vagrant/cumulus/Vagrantfile
+++ b/addons/vagrant/cumulus/Vagrantfile
@@ -104,6 +104,8 @@ node01_ip = user_vars['vms']['node01']['ip']
 node01_netmask = user_vars['vms']['node01']['netmask']
 node02_ip = user_vars['vms']['node02']['ip']
 node02_netmask = user_vars['vms']['node02']['netmask']
+node03_ip = user_vars['vms']['node03']['ip']
+node03_netmask = user_vars['vms']['node03']['netmask']
 
 Vagrant.configure("2") do |config|
 
@@ -203,7 +205,25 @@ Vagrant.configure("2") do |config|
             :libvirt__tunnel_local_port => "#{ 50001 + offset }",
             :libvirt__tunnel_ip => '127.0.0.1',
             :libvirt__tunnel_port => "#{ 60001 + offset }",
-            auto_config: false      
+            auto_config: false
+      # link for swp16 --> node03:ens6
+      device.vm.network "private_network",
+            :mac => "44:38:39:00:00:16",
+            :libvirt__tunnel_type => 'udp',
+            :libvirt__tunnel_local_ip => '127.0.0.1',
+            :libvirt__tunnel_local_port => "#{ 70000 + offset }",
+            :libvirt__tunnel_ip => '127.0.0.1',
+            :libvirt__tunnel_port => "#{ 80000 + offset }",
+            auto_config: false
+      # link for swp17 --> node03:ens7
+      device.vm.network "private_network",
+            :mac => "44:38:39:00:00:17",
+            :libvirt__tunnel_type => 'udp',
+            :libvirt__tunnel_local_ip => '127.0.0.1',
+            :libvirt__tunnel_local_port => "#{ 70001 + offset }",
+            :libvirt__tunnel_ip => '127.0.0.1',
+            :libvirt__tunnel_port => "#{ 80001 + offset }",
+            auto_config: false
       
     # Fixes "stdin: is not a tty" and "mesg: ttyname failed : Inappropriate ioctl for device"  messages --> https://github.com/mitchellh/vagrant/issues/1673
     device.vm.provision :shell , inline: "(sudo grep -q 'mesg n' /root/.profile 2>/dev/null && sudo sed -i '/mesg n/d' /root/.profile  2>/dev/null) || true;", privileged: false
@@ -259,6 +279,14 @@ udev_rule
      device.vm.provision :shell , :inline => <<-udev_rule
 echo "  INFO: Adding UDEV Rule: 44:38:39:00:00:15 --> swp15"
 echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="44:38:39:00:00:15", NAME="swp15", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
+udev_rule
+     device.vm.provision :shell , :inline => <<-udev_rule
+echo "  INFO: Adding UDEV Rule: 44:38:39:00:00:16 --> swp16"
+echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="44:38:39:00:00:16", NAME="swp16", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
+udev_rule
+     device.vm.provision :shell , :inline => <<-udev_rule
+echo "  INFO: Adding UDEV Rule: 44:38:39:00:00:17 --> swp17"
+echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="44:38:39:00:00:17", NAME="swp17", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
 udev_rule
 
      # to remap eth0 to vagrant management network (swp48) after udev rules have been wiped
@@ -510,5 +538,112 @@ vagrant_interface_rule
       ansible.verbose = ENV['VAGRANT_ANSIBLE_VERBOSE'] || false
     end
   end
+
+#   ##### DEFINE VM for node03 #####
+  config.vm.define "node03" do |device|
+
+    device.vm.hostname = "node03"
+
+    device.vm.box = inventory['all']['children']['nodes']['hosts']['node03']['box']
+    device.vm.box_version = inventory['all']['children']['nodes']['hosts']['node03']['box_version']
+
+    device.vm.provider :libvirt do |v|
+      v.nic_model_type = 'e1000'
+      v.memory = 1024
+
+    end
+    #   see note here: https://github.com/pradels/vagrant-libvirt#synced-folders
+    device.vm.synced_folder ".", "/vagrant", disabled: true
+
+    # NETWORK INTERFACES
+      # link for ens6 --> switch01:swp16 (vlan17)
+      device.vm.network "private_network",
+            :mac => "a0:00:00:00:00:32",
+            :libvirt__tunnel_type => 'udp',
+            :libvirt__tunnel_local_ip => '127.0.0.1',
+            :libvirt__tunnel_local_port => "#{ 80000 + offset }",
+            :libvirt__tunnel_ip => '127.0.0.1',
+            :libvirt__tunnel_port => "#{ 70000 + offset }",
+            :libvirt__iface_name => "ens6",
+            auto_config: false
+      # link for ens7 --> switch01:swp17 (dot1x port)
+      device.vm.network "private_network",
+            :mac => "00:03:00:11:13:01",
+            :libvirt__tunnel_type => 'udp',
+            :libvirt__tunnel_local_ip => '127.0.0.1',
+            :libvirt__tunnel_local_port => "#{ 80001 + offset }",
+            :libvirt__tunnel_ip => '127.0.0.1',
+            :libvirt__tunnel_port => "#{ 70001 + offset }",
+            auto_config: false
+
+    # Fixes "stdin: is not a tty" and "mesg: ttyname failed : Inappropriate ioctl for device"  messages --> https://github.com/mitchellh/vagrant/issues/1673
+    device.vm.provision :shell , inline: "(sudo grep -q 'mesg n' /root/.profile 2>/dev/null && sudo sed -i '/mesg n/d' /root/.profile  2>/dev/null) || true;", privileged: false
+
+    # install Venom using Ansible inventory generated by Vagrant
+    # inventory in inventory/ is not usable at this time (no IP on 172.17.17.X network)
+    device.vm.provision "pre_prov", type: 'ansible' do |ansible|
+      ansible.groups = {
+        "nodes" => ["node03"]
+      }
+      ansible.playbook = "playbooks/nodes_pre_prov.yml"
+      ansible.config_file = "ansible.cfg"
+      ansible.galaxy_role_file = "requirements.yml"
+      # redefine to disable --force option
+      # will use ${VAGRANT_DIR}/ansible.cfg for paths
+      ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file}"
+      # only for debug
+      ansible.verbose = ENV['VAGRANT_ANSIBLE_VERBOSE'] || false
+    end
+
+    # Run the Config specified in the Node Attributes
+    device.vm.provision :shell , privileged: false, :inline => 'echo "$(whoami)" > /tmp/normal_user'
+    device.vm.provision "config_node", type: "shell", path: "./helper_scripts/config_node03.sh",
+                        args: [ "#{node03_ip}", "#{node03_netmask}"]
+
+    # Install Rules for the interface re-map
+    device.vm.provision :shell , :inline => <<-delete_udev_directory
+if [ -d "/etc/udev/rules.d/70-persistent-net.rules" ]; then
+    rm -rfv /etc/udev/rules.d/70-persistent-net.rules &> /dev/null
+fi
+delete_udev_directory
+
+    device.vm.provision :shell , :inline => <<-udev_rule
+echo "  INFO: Adding UDEV Rule: a0:00:00:00:00:32 --> ens6"
+echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="a0:00:00:00:00:32", NAME="ens6", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
+udev_rule
+    device.vm.provision :shell , :inline => <<-udev_rule
+echo "  INFO: Adding UDEV Rule: 00:03:00:11:13:01 --> ens7"
+echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="00:03:00:11:13:01", NAME="ens7", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
+udev_rule
+
+     # fake to avoid ens6 being used by vagrant
+    device.vm.provision :shell , :inline => <<-vagrant_interface_rule
+echo "  INFO: Adding UDEV Rule: Vagrant interface = vagrant"
+echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{ifindex}=="2", NAME="vagrant", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
+echo "#### UDEV Rules (/etc/udev/rules.d/70-persistent-net.rules) ####"
+cat /etc/udev/rules.d/70-persistent-net.rules
+vagrant_interface_rule
+
+    # Run Any Platform Specific Code and Apply the interface Re-map
+    #   (may or may not perform a reboot depending on platform)
+    device.vm.provision :shell , :inline => $script
+
+    # Override common provisionner in master Vagrantfile
+    # to run **after** shell provisioning
+    # need to have identical name than common provisionner
+    device.vm.provision "site_ansible", type: 'ansible' do |ansible|
+      ansible.playbook = "site.yml"
+      ansible.config_file = "ansible.cfg"
+      ansible.inventory_path = "inventory"
+      ansible.galaxy_role_file = "requirements.yml"
+      # redefine to disable --force option
+      # will use ${VAGRANT_DIR}/ansible.cfg for paths
+      ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file}"
+      # only for debug
+      ansible.verbose = ENV['VAGRANT_ANSIBLE_VERBOSE'] || false
+    end
+  end
+
+
   
 end
