[Vagrant] inline l3 architecture with node02

diff --git a/addons/vagrant/cumulus/Vagrantfile b/addons/vagrant/cumulus/Vagrantfile
--- a/addons/vagrant/cumulus/Vagrantfile
+++ b/addons/vagrant/cumulus/Vagrantfile
@@ -103,7 +103,7 @@ Vagrant.configure("2") do |config|
 
     device.vm.provider :libvirt do |v|
       v.memory = 768
-
+      v.nic_adapter_count = 15
     end
     #   see note here: https://github.com/pradels/vagrant-libvirt#synced-folders
     device.vm.synced_folder ".", "/vagrant", disabled: true
@@ -169,6 +169,24 @@ Vagrant.configure("2") do |config|
             :libvirt__tunnel_ip => '127.0.0.1',
             :libvirt__tunnel_port => "#{ 40002 + offset }",
             auto_config: false
+      # link for swp14 --> node02:eth0
+      device.vm.network "private_network",
+            :mac => "44:38:39:00:00:14",
+            :libvirt__tunnel_type => 'udp',
+            :libvirt__tunnel_local_ip => '127.0.0.1',
+            :libvirt__tunnel_local_port => "#{ 50000 + offset }",
+            :libvirt__tunnel_ip => '127.0.0.1',
+            :libvirt__tunnel_port => "#{ 60000 + offset }",
+            auto_config: false
+      # link for swp15 --> node02:eth1
+      device.vm.network "private_network",
+            :mac => "44:38:39:00:00:15",
+            :libvirt__tunnel_type => 'udp',
+            :libvirt__tunnel_local_ip => '127.0.0.1',
+            :libvirt__tunnel_local_port => "#{ 50001 + offset }",
+            :libvirt__tunnel_ip => '127.0.0.1',
+            :libvirt__tunnel_port => "#{ 60001 + offset }",
+            auto_config: false      
       
     # Fixes "stdin: is not a tty" and "mesg: ttyname failed : Inappropriate ioctl for device"  messages --> https://github.com/mitchellh/vagrant/issues/1673
     device.vm.provision :shell , inline: "(sudo grep -q 'mesg n' /root/.profile 2>/dev/null && sudo sed -i '/mesg n/d' /root/.profile  2>/dev/null) || true;", privileged: false
@@ -215,6 +233,14 @@ udev_rule
 echo "  INFO: Adding UDEV Rule: 44:38:39:00:00:13 --> swp13"
 echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="44:38:39:00:00:13", NAME="swp13", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
 udev_rule
+     device.vm.provision :shell , :inline => <<-udev_rule
+echo "  INFO: Adding UDEV Rule: 44:38:39:00:00:14 --> swp14"
+echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="44:38:39:00:00:14", NAME="swp14", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
+udev_rule
+     device.vm.provision :shell , :inline => <<-udev_rule
+echo "  INFO: Adding UDEV Rule: 44:38:39:00:00:15 --> swp15"
+echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="44:38:39:00:00:15", NAME="swp15", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
+udev_rule
 
      # to remap eth0 to vagrant management network (swp48) after udev rules have been wiped
      device.vm.provision :shell , :inline => <<-vagrant_interface_rule
@@ -252,7 +278,7 @@ vagrant_interface_rule
     device.vm.box_version = inventory['all']['children']['nodes']['hosts']['node01']['box_version']
 
     device.vm.provider :libvirt do |v|
-      v.nic_model_type = 'e1000' 
+      v.nic_model_type = 'e1000'
       v.memory = 1024
 
     end
@@ -361,4 +387,111 @@ vagrant_interface_rule
       ansible.verbose = ENV['VAGRANT_ANSIBLE_VERBOSE'] || false
     end
   end
+
+#   ##### DEFINE VM for node02 #####
+  config.vm.define "node02" do |device|
+
+    device.vm.hostname = "node02"
+
+    device.vm.box = inventory['all']['children']['nodes']['hosts']['node02']['box']
+    device.vm.box_version = inventory['all']['children']['nodes']['hosts']['node02']['box_version']
+
+    device.vm.provider :libvirt do |v|
+      v.nic_model_type = 'e1000'
+      v.memory = 1024
+
+    end
+    #   see note here: https://github.com/pradels/vagrant-libvirt#synced-folders
+    device.vm.synced_folder ".", "/vagrant", disabled: true
+
+    # to run Venom tests
+    device.vm.synced_folder "../../t", "/src/t", type: "rsync", rsync__args: ["--verbose", "--archive", "--delete", "-z"]
+
+    # NETWORK INTERFACES
+      # link for eth0 --> switch01:swp14 (vlan17)
+      device.vm.network "private_network",
+            :mac => "a0:00:00:00:00:22",
+            :libvirt__tunnel_type => 'udp',
+            :libvirt__tunnel_local_ip => '127.0.0.1',
+            :libvirt__tunnel_local_port => "#{ 60000 + offset }",
+            :libvirt__tunnel_ip => '127.0.0.1',
+            :libvirt__tunnel_port => "#{ 50000 + offset }",
+            :libvirt__iface_name => "eth0",
+            auto_config: false
+      # link for eth1 --> switch01:swp15 (vlan18)
+      device.vm.network "private_network",
+            :mac => "00:03:00:11:12:01",
+            :libvirt__tunnel_type => 'udp',
+            :libvirt__tunnel_local_ip => '127.0.0.1',
+            :libvirt__tunnel_local_port => "#{ 60001 + offset }",
+            :libvirt__tunnel_ip => '127.0.0.1',
+            :libvirt__tunnel_port => "#{ 50001 + offset }",
+            auto_config: false
+
+    # Fixes "stdin: is not a tty" and "mesg: ttyname failed : Inappropriate ioctl for device"  messages --> https://github.com/mitchellh/vagrant/issues/1673
+    device.vm.provision :shell , inline: "(sudo grep -q 'mesg n' /root/.profile 2>/dev/null && sudo sed -i '/mesg n/d' /root/.profile  2>/dev/null) || true;", privileged: false
+
+    # Disable common Ansible provisionner in master Vagrantfile
+    device.vm.provision "ansible", type: 'ansible', run:"never" do |ansible|
+    end
+
+    # install Venom using Ansible inventory generated by Vagrant
+    # inventory in inventory/ is not usable at this time (no IP on 172.17.17.X network)
+    device.vm.provision "pre_prov", type: 'ansible' do |ansible|
+      ansible.groups = {
+        "nodes" => ["node02"]
+      }
+      ansible.playbook = "nodes_pre_prov.yml"
+      ansible.config_file = "ansible.cfg"
+      ansible.galaxy_role_file = "requirements.yml"
+      # only for debug
+      ansible.verbose = ENV['VAGRANT_ANSIBLE_VERBOSE'] || false
+    end
+
+    # Run the Config specified in the Node Attributes
+    device.vm.provision :shell , privileged: false, :inline => 'echo "$(whoami)" > /tmp/normal_user'
+    device.vm.provision "config_node", type: "shell", path: "./helper_scripts/config_node02.sh"
+
+
+    # Install Rules for the interface re-map
+    device.vm.provision :shell , :inline => <<-delete_udev_directory
+if [ -d "/etc/udev/rules.d/70-persistent-net.rules" ]; then
+    rm -rfv /etc/udev/rules.d/70-persistent-net.rules &> /dev/null
+fi
+rm -rfv /etc/udev/rules.d/70-persistent-net.rules &> /dev/null
+delete_udev_directory
+
+device.vm.provision :shell , :inline => <<-udev_rule
+echo "  INFO: Adding UDEV Rule: a0:00:00:00:00:22 --> eth0"
+echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="a0:00:00:00:00:22", NAME="eth0", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
+udev_rule
+     device.vm.provision :shell , :inline => <<-udev_rule
+echo "  INFO: Adding UDEV Rule: 00:03:00:11:12:02 --> eth1"
+echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="00:03:00:11:12:01", NAME="eth1", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
+udev_rule
+
+     # fake to avoid eth0 being used by vagrant
+     device.vm.provision :shell , :inline => <<-vagrant_interface_rule
+echo "  INFO: Adding UDEV Rule: Vagrant interface = vagrant"
+echo 'ACTION=="add", SUBSYSTEM=="net", ATTR{ifindex}=="2", NAME="vagrant", SUBSYSTEMS=="pci"' >> /etc/udev/rules.d/70-persistent-net.rules
+echo "#### UDEV Rules (/etc/udev/rules.d/70-persistent-net.rules) ####"
+cat /etc/udev/rules.d/70-persistent-net.rules
+vagrant_interface_rule
+
+    # Run Any Platform Specific Code and Apply the interface Re-map
+    #   (may or may not perform a reboot depending on platform)
+    device.vm.provision :shell , :inline => $script
+
+    # Override common provisionner in master Vagrantfile
+    # to run **after** shell provisioning
+    device.vm.provision "post_prov", type: 'ansible' do |ansible|
+      ansible.playbook = "site.yml"
+      ansible.config_file = "ansible.cfg"
+      ansible.inventory_path = "inventory"
+      ansible.galaxy_role_file = "requirements.yml"
+      # only for debug
+      ansible.verbose = ENV['VAGRANT_ANSIBLE_VERBOSE'] || false
+    end
+  end
+  
 end
